apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
      - env:
          - name: RUBYOPT
            value: W:no-deprecated -W:no-experimental
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
        args:
        - bash
        - -c
        #- while true; do sleep 30; done;
        -  rm -f tmp/pids/server.pid && bundle exec rake db:create && bundle exec rake
          db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'
        image: typo/api
        imagePullPolicy: Always
        name: api
        ports:
        - containerPort: 3000
        resources: {}
        #volumeMounts:
        #- mountPath: /usr/src/app
        #  name: api-claim0
      #restartPolicy: Always
      serviceAccountName: ""
      #volumes:
      #- name: api-claim0
      #  persistentVolumeClaim:
      #    claimName: api-claim0
status: {}
