apiVersion: v1
kind: ConfigMap
metadata:
  name: host-configmap
data:
  api_host: |
    VUE_APP_API_HOSTNAME=http://192.168.64.10:30000
  web_host: http://192.168.64.10:30808
  vue_dev_host: |
    module.exports = {
        devServer: {
          public: '192.168.64.10',
          disableHostCheck: true
        }
    }
