apiVersion: skaffold/v2beta2
kind: Config
metadata:
  name: concord
build:
  artifacts:
  - image: typo/api
    context: ruby
    sync:
      infer:
        - '**/*.rb'
  - image: typo/web
    context: vue
    sync:
      infer:
        - '**/*.js'
        - '**/*.vue'
deploy:
  kubectl:
    manifests:
    - host-configmap.yaml
    - api-deployment.yaml
    - api-secret.yaml
    - api-service.yaml
    - db-deployment.yaml
    - db-secret.yaml
    - db-service.yaml
    - web-deployment.yaml
    - web-service.yaml
